---

- include: prereqs_ubuntu_14.04.yml
  when: ansible_distribution_version == "14.04"

- include: prereqs_ubuntu_16.04.yml
  when: ansible_distribution_version == "16.04"

- name: download netatalk source code
  get_url: url={{ netatalk_url }} dest=/usr/src/netatalk-{{ netatalk_version }}.tar.gz

- name: unpack source code
  unarchive: src=/usr/src/netatalk-{{ netatalk_version }}.tar.gz dest=/usr/src copy=no

- name: configure
  shell: cd /usr/src/netatalk-{{ netatalk_version }} && ./configure --with-init-style=debian-sysv --without-libevent --without-tdb --with-cracklib --enable-krbV-uam --with-pam-confdir=/etc/pam.d --with-dbus-sysconf-dir=/etc/dbus-1/system.d --with-tracker-pkgconfig-version=0.16

- name: make
  shell: cd /usr/src/netatalk-{{ netatalk_version }} && make

- name: install
  shell: cd /usr/src/netatalk-{{ netatalk_version }} && checkinstall --pkgname=netatalk --default

- name: make sure timemachine folder exist
  file: path={{ timemachine_path }} state=directory mode=0755

- name: configure
  template: src=afp.conf.j2 dest=/usr/local/etc/afp.conf mode=0644
  notify:
    - restart netatalk

- name: enable netatalk on boot
  service: name=netatalk enabled=yes
