---
- name: install prereqs
  apt: name={{ item }} state=present
  with_items:
    - avahi-daemon
    - build-essential
    - libacl1-dev
    - libavahi-client-dev
    - libcrack2-dev
    - libdb-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libevent-dev
    - libgcrypt-dev
    - libglib2.0-dev
    - libkrb5-dev
    - libldap2-dev
    - libmysqlclient-dev
    - libpam0g-dev
    - libssl-dev
    - libtdb-dev
    - libtracker-miner-1.0-dev
    - libtracker-sparql-1.0-dev
    - libwrap0-dev
    - systemtap-sdt-dev
    - tracker
  tags: netatalk
